### ISSUE TITLE
Terminal blank

### ISSUE THREAD

**Issue by Karomatic** [IAmBatby/LethalLevelLoader#67]
With the new public beta v50, it is making the terminal not work. The screen is completely blank and you can't exit out of the terminal. If mod is removed, it takes away Aquatis and Orion.

**Comment by GhostIsCool64** [comment]
I've been having this same exact issue, it's so annoying I hope they fix it

**Comment by GhostIsCool64** [comment]
The most you can do is download 1.0.7 or some other version im not checking all of them. cuz it works, it just doesn't display the moon list for some reason...

**Comment by PRTYBEESTog** [comment]
Still persisting post-beta :/ Hope it gets fixed soon

**Comment by IAmBatby** [comment]
Hi, If your testing out the experimental v50 beta please report issues on the Lethal Company Modding discord where I have a thread about the matter! Not a big fan of Discord for forum type stuff in general but the beta is released so I can hopefully knock out issues asap and Discord is nice for me to help understand and troubleshoot these kind of errors, Thanks!

**Comment by dog199200** [comment]
Sadly the discord link is not working. May want to add an invite to the discord server as well. So I tested each version to see what would work and what wouldn't.

1.1.6 - Not Working - Blank in game terminal - Errors in log
1.1.5 - Not Working - Blank in game terminal - Errors in log
1.1.4 - Not Working - Blank in game terminal - Errors in log
1.1.3 - Not Working - Blank in game terminal - Errors in log
1.1.2 - Not Working - Blank in game terminal - Errors in log
1.1.1 - Not Working - Blank in game terminal - Errors in log
1.1.0 - Not Working - Blank in game terminal - Errors in log
1.0.7 and Earlier - Partially Working - Terminal Accessible - Cannot View Moons - No Errors in Log

**Comment by M0dds** [comment]
I would like a discord invite aswell, really waiting for the mod aswell :)

**Comment by AndreyMrovol** [comment]
https://discord.com/channels/1168655651455639582/1228961224126103632

**Comment by LimerBoy** [comment]
Try download this dll and replace old https://github.com/IAmBatby/LethalLevelLoader/tree/main/Thunderstore/plugins 
Worked for me on v50 with Westley moons also replace LethalExpansionCore to LethalExpansionCorePatch

**Comment by EthanRomine** [comment]
I fixed it: Download a mod called LethalModDataLib. For some reason it isn't listed as a dependancy on thunderstore but it does need it to work in the newer versions. Hope this helps.

**Comment by Optagonus** [comment]
I installed LethalModDataLib and it still isn't working, I'll be using the 1.0.7 version until they update it.

**Comment by jerseymaster2003** [comment]
Only issue i've come across with the Pineguys fix is that it doesn't seem to spawn any spike traps.  Everything else seems pretty stable though

**Comment by IAmBatby** [comment]
Pineguys reupload of that patch is not created by Pineguy nor is it a fully fledged fix, I'd personally suggest abstaining from using it.

**Comment by Kuroo2021** [comment]
> Sadly the discord link is not working. May want to add an invite to the discord server as well. So I tested each version to see what would work and what wouldn't.
> 
> 1.1.6 - Not Working - Blank in game terminal - Errors in log 1.1.5 - Not Working - Blank in game terminal - Errors in log 1.1.4 - Not Working - Blank in game terminal - Errors in log 1.1.3 - Not Working - Blank in game terminal - Errors in log 1.1.2 - Not Working - Blank in game terminal - Errors in log 1.1.1 - Not Working - Blank in game terminal - Errors in log 1.1.0 - Not Working - Blank in game terminal - Errors in log 1.0.7 and Earlier - Partially Working - Terminal Accessible - Cannot View Moons - No Errors in Log

Posting the errors in the logs maybe helpfully as well. 📦

**Comment by 1450143535** [comment]
On April 20th today, the LE author re uploaded a LE preview version on Thunderstore. Will future LLL versions reconsider compatibility with LE due to this?

**Comment by marcoboy123** [comment]
Also same, with this (I dont even have a G Drive, wth?) 

```
[Info   : Unity Log] Set interminalmenu to true: True
[Info   : Unity Log] Caught error while entering computer terminal. Exiting player from terminal. Error: System.NullReferenceException: Object reference not set to an instance of an object
  at LethalLevelLoader.Patches.TerminalLoadNewNode_Prefix (Terminal __instance, TerminalNode& node) [0x00001] in G:\Unity\LethalLevelLoader\LethalLevelLoader\General\Patches.cs:273
  at (wrapper dynamic-method) Terminal.DMD<Terminal::LoadNewNode>(Terminal,TerminalNode)
  at (wrapper dynamic-method) Terminal.DMD<Terminal::BeginUsingTerminal>(Terminal)
[Info   : Unity Log] Quit terminal; inTerminalMenu true?: {playerScript.inTerminalMenu}
```

**Comment by IAmBatby** [comment]
Closed as Lethal Expansion is now deprecated.
