### ISSUE TITLE
loading save causes items to change

### ISSUE THREAD

**Issue by Jeffinator06** [IAmBatby/LethalLevelLoader#73]
whenever i load a save, every item on the ship gets changed to something else. it seems to be pretty random, as 2 different objects both got turned into ladders (pro flashlight and shovel turned into the ladders). im 99% certain its something with LLL as ive tested with LLL on and off and the issue only seems to occur when LLL is active

i have no screenshot of the ORIGINAL items, but i do know what they were. originally these items were a pro flashlight, shovel, jetpack and stun grenade. this is loading into the save for the first time with LLL active
![20240425102645_1](https://github.com/IAmBatby/LethalLevelLoader/assets/168121813/b127e89e-c4ab-47ee-89ce-fc02b8716448)

this is loading into the save a second time. as you can see, the items have changed
![20240425102658_1](https://github.com/IAmBatby/LethalLevelLoader/assets/168121813/a1f779f1-c8fc-4c6d-8941-6865b8b0d3e9)

**Comment by ZD-ChaofanJ** [comment]
Can confirm. This is most likely related to LethalLevelLoader, one or more of it's Dependencies, or both. This happens regardless of mod combinations. This issue occurs even when loading LethalLevelLoader and it's Dependencies by themselves.

**Comment by ZD-ChaofanJ** [comment]
Looks like this issue has been fixed in LethalLevelLoader v1.2.2.

**Comment by dopadream** [comment]
> Looks like this issue appears to have been fixed in LethalLevelLoader v1.2.2.

Pretty sure it still happens in that version, however a pull request appears to fix this issue: https://github.com/IAmBatby/LethalLevelLoader/pull/76

**Comment by Jeffinator06** [comment]
> Can confirm. This is most likely related to LethalLevelLoader, one or more of it's Dependencies, or both. This happens regardless of mod combinations. This issue occurs even when loading LethalLevelLoader and it's Dependencies by themselves.

its something with LLL, as the issue only occurs with it active. the dependencies are fine from what ive gathered

**Comment by IAmBatby** [comment]
Resolved in future versions of the project. It's possible this issue may still occur with custom Item's implemented via LethalLib but unfortunately I do not intend to support usage of that and cannot promise stability in that usage.

**Comment by melvyn2** [comment]
why is this closed when no fix is public? The most recent commit on any branch was more than a month ago...
